brew "direnv"
# brew "git-delta"
brew "starship"
brew "stow"
brew "tmux"
brew "uv"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "go"
brew "fnm"
brew "tailscale"
brew "anomalyco/tap/opencode"
brew "llama.cpp"

## Neovim ##
brew "lua-language-server"
brew "tree-sitter-cli"
brew "fzf"
brew "fd"
brew "rg"
brew "bat"
brew "git-delta"
brew "chafa"

# casks #

## in 'dock order' ##
cask "firefox"
cask "bitwarden"
cask "ghostty"
cask "dbeaver-community"
cask "docker-desktop"
cask "linear-linear"
cask "google-chrome"
cask "notion"
cask "adobe-creative-cloud"
cask "ableton-live-suite"
cask "spotify"

## not in dock ##
cask "logi-options+"
cask "logitech-g-hub"

## not in dock ##
cask "claude-code"
cask "raycast"
